const fmt=(v,d=1)=>{const n=Number(v);return Number.isFinite(n)?`${n.toFixed(d)}%`:'—'};
const months=['J','F','M','A','M','J','J','A','S','O','N','D'];
const badgeClass=(type,value)=>`${type}-${String(value||'unknown').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown'}`;
const badge=(type,value)=>value?`<span class="badge ${type} ${badgeClass(type,value)}">${value}</span>`:'';
function card(s){
 const rs=s.monthly_returns||[]; const valid=x=>x.return_pct!=null&&x.return_pct!==''&&Number.isFinite(Number(x.return_pct)); const values=rs.filter(valid).map(x=>Number(x.return_pct)); const max=Math.max(1,...values.map(Math.abs));
 const bars=rs.map(r=>{const v=Number(r.return_pct),safe=valid(r),h=safe?Math.max(2,Math.min(55,Math.abs(v)/max*55)):2;return `<div class="m" title="${r.year}-${String(r.month).padStart(2,'0')}: ${safe?`${v}%`:'—'}"><div class="barwrap"><div class="bar ${safe&&v<0?'neg':''}" style="height:${h}px"></div></div><div class="mval">${safe?`${v>0?'+':''}${v.toFixed(1)}`:'—'}</div><div class="mlabel">${months[r.month-1]}${String(r.year).slice(2)}</div></div>`}).join('');
 return `<article class="card"><div class="top"><img class="avatar" src="${s.avatar_url||''}" alt=""><div class="title"><h2>${s.name}</h2><div class="provider">${s.provider||'—'}</div><div class="badges">${badge('priority',s.priority)}${badge('role',s.role)}</div></div><div class="status">${(s.status||'WATCH').split('/')[0].trim()}</div></div><div class="metrics"><div class="metric"><b>${fmt(s.baseline_growth_pct)}</b><span>Growth</span></div><div class="metric"><b>${fmt(s.baseline_max_dd_pct)}</b><span>Max DD</span></div><div class="metric" title="2026 median monthly return scaled linearly to 20% max DD"><b>${fmt(s.normalized_monthly_20dd_pct)}</b><span>NORM/MO</span></div><div class="metric"><b>${fmt(s.baseline_win_rate_pct)}</b><span>Win rate</span></div><div class="metric"><b>${fmt(s.baseline_deposit_load_pct)}</b><span>Load</span></div></div><div class="fingerprint">${s.risk_fingerprint||''}</div><div class="months">${bars}</div><div class="foot"><span>T0 ${s.t0_date}</span><span>${s.price_monthly_usd?`$${s.price_monthly_usd}/mo`:''}</span></div></article>`
}
fetch('/api/signals').then(r=>r.json()).then(x=>{if(x.error)throw new Error(x.error);document.getElementById('count').textContent=`${x.signals.length} baselines`;document.getElementById('app').innerHTML=`<div class="grid">${x.signals.map(card).join('')}</div>`}).catch(e=>document.getElementById('app').innerHTML=`<div class="error">${e.message}</div>`);
